if: tag IS blank # Don't build tags

dist: xenial
env:
  - DOCKER_CLI_EXPERIMENTAL="enabled"
jobs:
  include:
    - stage: test
      script:
        - make
    - stage: deploy-image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - sudo docker run --privileged linuxkit/binfmt:v0.6
        - make docker-push
stages:
  - name: test
    if: type = pull_request OR (type = push AND branch != master)
  - name: deploy-image
    if: type = push AND branch = master
